on: [push, pull_request]
name: Lint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install libbfd
        run: |
          sudo apt-get update && sudo apt-get install -y binutils
          sudo ln -s /usr/lib/x86_64-linux-gnu/libbfd-2.42-system.so /usr/lib/x86_64-linux-gnu/libbfd-2.38-system.so

      - name: checkout
        uses: actions/checkout@v4

      - name: Install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Install lua-language-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd
          gh release download -R sumneko/lua-language-server -p '*-linux-x64.tar.gz' -D lua-language-server
          tar xzf lua-language-server/* -C lua-language-server
          echo "${PWD}/lua-language-server/bin" >> $GITHUB_PATH
          export PATH="${PWD}/lua-language-server/bin:${PATH}"
          lua-language-server --version

      - name: Install emmylua_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd
          gh release download -R EmmyLuaLs/emmylua-analyzer-rust -p emmylua_check-linux-x64.tar.gz -D emmylua_check
          tar xzf emmylua_check/* -C emmylua_check
          echo "${PWD}/emmylua_check/" >> $GITHUB_PATH
          export PATH="${PWD}/emmylua_check/:${PATH}"
          emmylua_check --version

      - name: Lint
        run: |
          make deps
          make lint
          make emmylua-check
